# Start with Kit Base image
FROM nvcr.io/nvidia/omniverse/kit:103.5.1

# Install services dependencies on image (omni.services does not ship with Kit)
# This code is pulled from a extension registry and the --ext-precache-mode will pull down the extensions and exit.
RUN /opt/nvidia/omniverse/kit-sdk-launcher/kit \
  --ext-precache-mode \
  --enable omni.services.core \
  --enable omni.services.transport.server.http \
  --/exts/omni.kit.registry.nucleus/registries/0/name=kit/services \
  --/exts/omni.kit.registry.nucleus/registries/0/url=https://dw290v42wisod.cloudfront.net/exts/kit/services \
  --allow-root

# Add script to image
COPY hello_world.py /hello_world.py

# Declare "intention" for container to use port 8011 at runtime
EXPOSE 8011/tcp

# Configure a container as an executable
ENTRYPOINT [ \
  "/opt/nvidia/omniverse/kit-sdk-launcher/kit", \
  "--exec", "hello_world.py", \
  "--enable omni.services.core", \ 
  "--enable", "omni.services.transport.server.http", \
  "--allow-root"]