location            = "eastus"
namespace           = "ovfarm"
project             = "omniverse-farm-poc"
resource_group_name = "dt-sandbox-resources"
env                 = "dev"
ssh_public_key      = "~/.ssh/id_rsa.pub"